version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo starting build for cloud-atlas-ui environment $environment
      - echo Installing source NPM dependencies...
      - npm install --force
      - npm install -g @angular/cli
  build:
    commands:
      - ng build cloud-atlas-ui --configuration $environment
  post_build:
    commands:
      - cd dist
      - aws s3 sync ./ s3://cloud-atlas-$environment-ui --delete
artifacts:
  files:
    - "**/*"
  base-directory: "dist"
  discard-paths: no
