export const environment = {
  environment: 'demo',
  app_name: 'cloud-atlas-dev',
  api_endpoint: 'https://d7k7jlwi56.execute-api.us-east-1.amazonaws.com/demo/api',
  authority: 'https://cognito-idp.us-east-1.amazonaws.com/us-east-1_8Oo7AeC7Q',
  auth_well_known_endpoint_url: 'https://cognito-idp.us-east-1.amazonaws.com/us-east-1_8Oo7AeC7Q',
  redirect_url: 'http://localhost:4200/redirect',
  post_logout_redirect_uri: 'http://localhost:4200',
  client_id: '7algq35flinuu94315dui7o1ot',
  renew_time_before_token_expires: '30',
  region: 'us-east-1',
  user_pool_id: 'us-east-1_8Oo7AeC7Q',
  max_image_file_size_in_bytes: '20971520',
  google_map_id: '6b0e9677f8a58360',
  google_maps_api_key: 'AIzaSyAN_7h_8vVPFJB4d_j8OmS1dnYa0IyN5yg',
  id_token_expiration_in_miliseconds: '86400000',
  logout_uri: 'http://localhost:4200',
  maps_limit: '25',
  markers_limit: '100',
  images_limit: '25',
};
