export const environment = {
  environmentName: 'local',
  appName: 'cloud-atlas-dev',
  api_endpoint: 'http://localhost:3000',
  authority: 'https://cognito-idp.us-east-1.amazonaws.com/us-east-1_szwZtfXgl',
  authWellknownEndpointUrl: 'https://cognito-idp.us-east-1.amazonaws.com/us-east-1_szwZtfXgl',
  redirectUrl: 'http://localhost:4200/redirect',
  postLogoutRedirectUri: 'http://localhost:4200',
  clientId: '7ocqnpg4b45h239cc3p9pke5kf',
  renewTimeBeforeTokenExpiresInSeconds: '30',
  region: 'us-east-1',
  userPoolId: 'us-east-1_szwZtfXgl',
  maxImageFileSizeInBytes: '20971520',
  googleMapId: '6b0e9677f8a58360',
  googleMapsApiKey: 'AIzaSyAN_7h_8vVPFJB4d_j8OmS1dnYa0IyN5yg',
  idTokenExpirationInMiliseconds: '86400000',
  logoutUri: 'http://localhost:4200',
  mapsLimit: '25',
  markersLimit: '100',
  imagesLimit: '25',
};
