export const environment = {
  environmentName: 'demo',
  appName: 'cloud-atlas-dev',
  api_endpoint: 'https://bbtdpuu2yb.execute-api.us-east-1.amazonaws.com/demo/api',
  authority: 'https://cognito-idp.us-east-1.amazonaws.com/us-east-1_neNghB1gw',
  authWellknownEndpointUrl: 'https://cognito-idp.us-east-1.amazonaws.com/us-east-1_neNghB1gw',
  redirectUrl: 'http://localhost:4200/redirect',
  postLogoutRedirectUri: 'http://localhost:4200',
  clientId: '2sb6ijn4chp2ghh9q1f5okf78v',
  renewTimeBeforeTokenExpiresInSeconds: '30',
  region: 'us-east-1',
  userPoolId: 'us-east-1_neNghB1gw',
  maxImageFileSizeInBytes: '20971520',
  googleMapId: '6b0e9677f8a58360',
  googleMapsApiKey: 'AIzaSyAN_7h_8vVPFJB4d_j8OmS1dnYa0IyN5yg',
  idTokenExpirationInMiliseconds: '86400000',
  logoutUri: 'http://localhost:4200',
  mapsLimit: '25',
  markersLimit: '100',
  imagesLimit: '25',
};
