export const environment = {
  environmentName: 'demo',
  appName: 'cloud-atlas-demo',
  api_endpoint: 'https://q306hjshu2.execute-api.us-east-1.amazonaws.com/demo',
  authority: 'https://cognito-idp.us-east-1.amazonaws.com/us-east-1_VCtnNvota',
  authWellknownEndpointUrl: 'https://cognito-idp.us-east-1.amazonaws.com/us-east-1_VCtnNvota',
  redirectUrl: 'http://localhost:4200/redirect',
  postLogoutRedirectUri: 'http://localhost:4200',
  clientId: 'nrdg20ifdcabn2nceqrn2c0c9',
  renewTimeBeforeTokenExpiresInSeconds: '30',
  region: 'us-east-1',
  userPoolId: 'us-east-1_VCtnNvota',
  maxImageFileSizeInBytes: '20971520',
  googleMapId: '6b0e9677f8a58360',
  googleMapsApiKey: 'AIzaSyAN_7h_8vVPFJB4d_j8OmS1dnYa0IyN5yg',
  idTokenExpirationInMiliseconds: '86400000',
  logoutUri: 'http://localhost:4200',
  mapsLimit: '25',
  markersLimit: '25',
  imagesLimit: '25',
};
