export const environment = {
  name: 'test',
  appName: 'cloud-atlas-test',
  api_endpoint: 'https://c7l2a05lha.execute-api.us-east-1.amazonaws.com/test',
  authority: 'https://cognito-idp.us-east-1.amazonaws.com/us-east-1_IOO5MN0pD',
  authWellknownEndpointUrl: 'https://cognito-idp.us-east-1.amazonaws.com/us-east-1_IOO5MN0pD',
  redirectUrl: 'http://localhost:4200/redirect',
  postLogoutRedirectUri: 'http://localhost:4200',
  clientId: '684qgps2bdt01dn5l1dbbr64jh',
  renewTimeBeforeTokenExpiresInSeconds: 30,
  region: 'us-east-1',
  userPoolId: 'us-east-1_IOO5MN0pD',
  maxImageFileSizeInBytes: 15728640,
  googleMapId: '6b0e9677f8a58360',
  googleMapsApiKey: 'AIzaSyCymGXjavlTc6D5maGwEqUXZKYCO6kiGxw',
  idTokenExpirationInMiliseconds: 86400000,
  logoutUri: 'http://localhost:4200',
  mapsLimit: 25,
  markersLimit: 25,
  imagesLimit: 25,
};
