export const environment = {
  environmentName: '',
  appName: '',
  api_endpoint: '',
  authority: '',
  authWellknownEndpointUrl: '',
  redirectUrl: '',
  postLogoutRedirectUri: '',
  clientId: '',
  renewTimeBeforeTokenExpiresInSeconds: '',
  region: '',
  userPoolId: '',
  maxImageFileSizeInBytes: '',
  googleMapId: '',
  googleMapsApiKey: '',
  idTokenExpirationInMiliseconds: '',
  logoutUri: '',
  mapsLimit: '',
  markersLimit: '',
  imagesLimit: '',
};
