export const environment = {
  name: 'local',
  appName: 'cloud-atlas-dev',
  api_endpoint: 'http://localhost:3000',
  authority: 'https://cognito-idp.us-east-1.amazonaws.com/us-east-1_szwZtfXgl',
  authWellknownEndpointUrl: 'https://cognito-idp.us-east-1.amazonaws.com/us-east-1_szwZtfXgl',
  redirectUrl: 'http://localhost:4200/redirect',
  postLogoutRedirectUri: 'http://localhost:4200',
  clientId: '7ocqnpg4b45h239cc3p9pke5kf',
  renewTimeBeforeTokenExpiresInSeconds: 30,
  region: 'us-east-1',
  userPoolId: 'us-east-1_szwZtfXgl',
  maxImageFileSizeInBytes: 15728640,
  googleMapId: '6b0e9677f8a58360',
  googleMapsApiKey: 'AIzaSyCymGXjavlTc6D5maGwEqUXZKYCO6kiGxw',
  idTokenExpirationInMiliseconds: 86400000,
  logoutUri: 'http://localhost:4200',
  mapsLimit: 25,
  markersLimit: 25,
  imagesLimit: 25,
};
