export const environment = {
  environment_name: '',
  app_name: '',
  api_endpoint: '',
  authority: '',
  auth_well_known_endpoint_url: '',
  redirect_url: '',
  post_logout_redirect_uri: '',
  client_id: '',
  renew_time_before_token_expires_in_seconds: '',
  region: '',
  user_pool_id: '',
  max_image_file_size_in_bytes: '',
  google_map_id: '',
  google_maps_api_key: '',
  id_token_expiration_in_miliseconds: '',
  logout_uri: '',
  maps_limit: '',
  markers_limit: '',
  images_limit: '',
};
