export const environment = {
  environmentName: '',
  appName: '',
  api_endpoint: '',
  authority: '',
  authWellknownEndpointUrl: '',
  redirectUrl: '',
  postLogoutRedirectUri: '',
  clientId: '',
  renewTimeBeforeTokenExpiresInSeconds: 0,
  region: '',
  userPoolId: '',
  maxImageFileSizeInBytes: 0,
  googleMapId: '',
  googleMapsApiKey: '',
  idTokenExpirationInMiliseconds: 0,
  logoutUri: '',
  mapsLimit: 0,
  markersLimit: 0,
  imagesLimit: 0,
};
