export const environment = {
  environmentName: 'test',
  appName: 'cloud-atlas-test',
  api_endpoint: 'https://lhsrfo30ae.execute-api.us-east-1.amazonaws.com/test',
  authority: 'https://cognito-idp.us-east-1.amazonaws.com/us-east-1_JGAWV4cuh',
  authWellknownEndpointUrl: 'https://cognito-idp.us-east-1.amazonaws.com/us-east-1_JGAWV4cuh',
  redirectUrl: 'http://localhost:4200/redirect',
  postLogoutRedirectUri: 'http://localhost:4200',
  clientId: '6rtk55jurfj7ak6a620fi9rqd8',
  renewTimeBeforeTokenExpiresInSeconds: '30',
  region: 'us-east-1',
  userPoolId: 'us-east-1_JGAWV4cuh',
  maxImageFileSizeInBytes: '15728640',
  googleMapId: '6b0e9677f8a58360',
  googleMapsApiKey: 'AIzaSyCymGXjavlTc6D5maGwEqUXZKYCO6kiGxw',
  idTokenExpirationInMiliseconds: '86400000',
  logoutUri: 'http://localhost:4200',
  mapsLimit: '25',
  markersLimit: '25',
  imagesLimit: '25',
};
