export const environment = {
  environment: 'prod',
  app_name: 'cloud-atlas-prod',
  api_endpoint: 'https://b6pxps4sf1.execute-api.us-east-1.amazonaws.com/prod/api',
  authority: 'https://cognito-idp.us-east-1.amazonaws.com/us-east-1_wFeMmnr1w',
  auth_well_known_endpoint_url: 'https://cognito-idp.us-east-1.amazonaws.com/us-east-1_wFeMmnr1w',
  redirect_url: 'https://cloud-atlas.net/redirect',
  post_logout_redirect_uri: 'https://cloud-atlas.net',
  client_id: '9bgjejtidnrv5k916cje3it8o',
  renew_time_before_token_expires: '30',
  region: 'us-east-1',
  user_pool_id: 'us-east-1_wFeMmnr1w',
  max_image_file_size_in_bytes: '20971520',
  google_map_id: '6b0e9677f8a58360',
  google_maps_api_key: 'AIzaSyCMgmEuJJOQ2KE0ze1XdBqF1Xv4mxplupA',
  id_token_expiration_in_miliseconds: '86400000',
  logout_uri: 'https://cloud-atlas.net',
  maps_limit: '25',
  markers_limit: '25',
  images_limit: '25',
};
