export const environment = {
  environmentName: 'test',
  appName: 'cloud-atlas-test',
  api_endpoint: 'https://5oi3tgtev9.execute-api.us-east-1.amazonaws.com/test',
  authority: 'https://cognito-idp.us-east-1.amazonaws.com/us-east-1_E0cRkWXvn',
  authWellknownEndpointUrl: 'https://cognito-idp.us-east-1.amazonaws.com/us-east-1_E0cRkWXvn',
  redirectUrl: 'http://localhost:4200/redirect',
  postLogoutRedirectUri: 'http://localhost:4200',
  clientId: '7eshf00bau618k9j1d2vhcbdp5',
  renewTimeBeforeTokenExpiresInSeconds: 30,
  region: 'us-east-1',
  userPoolId: 'us-east-1_E0cRkWXvn',
  maxImageFileSizeInBytes: 15728640,
  googleMapId: '6b0e9677f8a58360',
  googleMapsApiKey: 'AIzaSyCymGXjavlTc6D5maGwEqUXZKYCO6kiGxw',
  idTokenExpirationInMiliseconds: 86400000,
  logoutUri: 'http://localhost:4200',
  mapsLimit: 25,
  markersLimit: 25,
  imagesLimit: 25,
};
